Sima\SmfForumBundle\Entity\SmfBoards:
    type: entity
    table: smf_boards
    indexes:
        ID_PARENT:
            columns:
                - id_parent
        ID_MSG_UPDATED:
            columns:
                - id_msg_updated
    uniqueConstraints:
        categories:
            columns:
                - id_cat
                - id_board
        children:
            columns:
                - child_level
                - id_parent
                - board_order
                - id_board
    id:
        idBoard:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_board
            generator:
                strategy: IDENTITY
    fields:
        idCat:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: id_cat
        childLevel:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: child_level
        idParent:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_parent
        boardOrder:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: board_order
        idLastMsg:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_last_msg
        idMsgUpdated:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_msg_updated
        lastupdated:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: lastUpdated
        memberGroups:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: '-1,0'
            column: member_groups
        idProfile:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            default: '1'
            column: id_profile
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        description:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        numTopics:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: num_topics
        numPosts:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: num_posts
        countPosts:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: count_posts
        idTheme:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: id_theme
        overrideTheme:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: override_theme
        boardText:
            type: string
            nullable: false
            length: 120
            fixed: false
            comment: ''
            default: ''
            column: board_text
        redirect:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        unapprovedPosts:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: unapproved_posts
        unapprovedTopics:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: unapproved_topics
    lifecycleCallbacks: {  }
