Sima\SmfForumBundle\Entity\SmfBanGroups:
    type: entity
    table: smf_ban_groups
    id:
        idBanGroup:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_ban_group
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
        banTime:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: ban_time
        expireTime:
            type: integer
            nullable: true
            unsigned: true
            comment: ''
            column: expire_time
        cannotAccess:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: cannot_access
        cannotRegister:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: cannot_register
        cannotPost:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: cannot_post
        cannotLogin:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: cannot_login
        reason:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        notes:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
