Sima\SmfForumBundle\Entity\SmfCalendar:
    type: entity
    table: smf_calendar
    indexes:
        startDate:
            columns:
                - start_date
        endDate:
            columns:
                - end_date
        topic:
            columns:
                - id_topic
                - id_member
    id:
        idEvent:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_event
            generator:
                strategy: IDENTITY
    fields:
        startDate:
            type: date
            nullable: false
            comment: ''
            default: '0001-01-01'
            column: start_date
        idBoard:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_board
        idTopic:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_topic
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        idMember:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_member
        endDate:
            type: date
            nullable: false
            comment: ''
            default: '0001-01-01'
            column: end_date
    lifecycleCallbacks: {  }
