Sima\SmfForumBundle\Entity\SmfCategories:
    type: entity
    table: smf_categories
    id:
        idCat:
            type: boolean
            nullable: false
            comment: ''
            id: true
            column: id_cat
            generator:
                strategy: IDENTITY
    fields:
        catOrder:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: cat_order
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        canCollapse:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: can_collapse
    lifecycleCallbacks: {  }
