Sima\SmfForumBundle\Entity\SmfMembergroups:
    type: entity
    table: smf_membergroups
    indexes:
        minPosts:
            columns:
                - min_posts
    id:
        idGroup:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_group
            generator:
                strategy: IDENTITY
    fields:
        groupName:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
            default: ''
            column: group_name
        description:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        onlineColor:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            default: ''
            column: online_color
        minPosts:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '-1'
            column: min_posts
        maxMessages:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: max_messages
        stars:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        groupType:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: group_type
        hidden:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        idParent:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '-2'
            column: id_parent
    lifecycleCallbacks: {  }
