Sima\SmfForumBundle\Entity\SmfMessages:
    type: entity
    table: smf_messages
    indexes:
        ID_TOPIC:
            columns:
                - id_topic
        participation:
            columns:
                - id_member
                - id_topic
        showPosts:
            columns:
                - id_member
                - id_board
        ipIndex:
            columns:
                - poster_ip
                - id_topic
        approved:
            columns:
                - approved
        id_member_msg:
            columns:
                - id_member
                - approved
                - id_msg
        current_topic:
            columns:
                - id_topic
                - id_msg
                - id_member
                - approved
        related_ip:
            columns:
                - id_member
                - poster_ip
                - id_msg
        recherche:
            columns:
                - subject
                - body
    uniqueConstraints:
        topic:
            columns:
                - id_topic
                - id_msg
        ID_BOARD:
            columns:
                - id_board
                - id_msg
        ID_MEMBER:
            columns:
                - id_member
                - id_msg
    id:
        idMsg:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_msg
            generator:
                strategy: IDENTITY
    fields:
        idTopic:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_topic
        idBoard:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_board
        posterTime:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: poster_time
        idMember:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_member
        idMsgModified:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_msg_modified
        subject:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        posterName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: poster_name
        posterEmail:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: poster_email
        posterIp:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: poster_ip
        smileysEnabled:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: smileys_enabled
        modifiedTime:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: modified_time
        modifiedName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: modified_name
        body:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        icon:
            type: string
            nullable: false
            length: 16
            fixed: false
            comment: ''
            default: xx
        approved:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
    lifecycleCallbacks: {  }
