Sima\SmfForumBundle\Entity\SmfPolls:
    type: entity
    table: smf_polls
    id:
        idPoll:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_poll
            generator:
                strategy: IDENTITY
    fields:
        question:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        votingLocked:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: voting_locked
        maxVotes:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: max_votes
        expireTime:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: expire_time
        hideResults:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: hide_results
        changeVote:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: change_vote
        idMember:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_member
        posterName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: poster_name
        guestVote:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: guest_vote
        numGuestVoters:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: num_guest_voters
        resetPoll:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: reset_poll
    lifecycleCallbacks: {  }
