Sima\SmfForumBundle\Entity\SmfPmRecipients:
    type: entity
    table: smf_pm_recipients
    uniqueConstraints:
        ID_MEMBER:
            columns:
                - id_member
                - deleted
                - id_pm
    id:
        idPm:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            id: true
            column: id_pm
        idMember:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            id: true
            column: id_member
    fields:
        bcc:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        isRead:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: is_read
        deleted:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        labels:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
            default: '-1'
        isNew:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: is_new
    lifecycleCallbacks: {  }
