Sima\SmfForumBundle\Entity\SmfPrettyTopicUrls:
    type: entity
    table: smf_pretty_topic_urls
    uniqueConstraints:
        pretty_url:
            columns:
                - pretty_url
    id:
        idTopic:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_topic
            generator:
                strategy: IDENTITY
    fields:
        prettyUrl:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
            column: pretty_url
    lifecycleCallbacks: {  }
