Sima\SmfForumBundle\Entity\SmfPermissions:
    type: entity
    table: smf_permissions
    id:
        idGroup:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            id: true
            column: id_group
        permission:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            default: ''
            id: true
    fields:
        addDeny:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
            column: add_deny
    lifecycleCallbacks: {  }
