Sima\SmfForumBundle\Entity\SmfPersonalMessages:
    type: entity
    table: smf_personal_messages
    indexes:
        ID_MEMBER:
            columns:
                - id_member_from
                - deleted_by_sender
        msgtime:
            columns:
                - msgtime
        id_pm_head:
            columns:
                - id_pm_head
    id:
        idPm:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_pm
            generator:
                strategy: IDENTITY
    fields:
        idPmHead:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_pm_head
        idMemberFrom:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_member_from
        deletedBySender:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: deleted_by_sender
        fromName:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: from_name
        msgtime:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
        subject:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        body:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
