Sima\SmfForumBundle\Entity\SmfPollChoices:
    type: entity
    table: smf_poll_choices
    id:
        idPoll:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            id: true
            column: id_poll
        idChoice:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            id: true
            column: id_choice
    fields:
        label:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        votes:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
