Sima\SmfForumBundle\Entity\SmfSubscriptions:
    type: entity
    table: smf_subscriptions
    indexes:
        active:
            columns:
                - active
    id:
        idSubscribe:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_subscribe
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
            default: ''
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        cost:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        length:
            type: string
            nullable: false
            length: 6
            fixed: false
            comment: ''
            default: ''
        idGroup:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: id_group
        addGroups:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
            default: ''
            column: add_groups
        active:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
        repeatable:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        allowPartial:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: allow_partial
        reminder:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        emailComplete:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: email_complete
    lifecycleCallbacks: {  }
