Sima\SmfForumBundle\Entity\SmfSettings:
    type: entity
    table: smf_settings
    id:
        variable:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
