Sima\SmfForumBundle\Entity\SmfSmileys:
    type: entity
    table: smf_smileys
    id:
        idSmiley:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_smiley
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
            default: ''
        filename:
            type: string
            nullable: false
            length: 48
            fixed: false
            comment: ''
            default: ''
        description:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
            default: ''
        smileyRow:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: smiley_row
        smileyOrder:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: smiley_order
        hidden:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
    lifecycleCallbacks: {  }
