Sima\SmfForumBundle\Entity\SmfTopics:
    type: entity
    table: smf_topics
    indexes:
        isSticky:
            columns:
                - is_sticky
        ID_BOARD:
            columns:
                - id_board
        approved:
            columns:
                - approved
        member_started:
            columns:
                - id_member_started
                - id_board
        last_message_sticky:
            columns:
                - id_board
                - is_sticky
                - id_last_msg
        board_news:
            columns:
                - id_board
                - id_first_msg
    uniqueConstraints:
        poll:
            columns:
                - id_poll
                - id_topic
        firstMessage:
            columns:
                - id_first_msg
                - id_board
        lastMessage:
            columns:
                - id_last_msg
                - id_board
    id:
        idTopic:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            column: id_topic
            generator:
                strategy: IDENTITY
    fields:
        isSticky:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: is_sticky
        idBoard:
            type: smallint
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_board
        idFirstMsg:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_first_msg
        idLastMsg:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_last_msg
        idMemberStarted:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_member_started
        idMemberUpdated:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_member_updated
        idPoll:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: id_poll
        numReplies:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: num_replies
        numViews:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: num_views
        locked:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        unapprovedPosts:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: unapproved_posts
        approved:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
        idPreviousBoard:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: id_previous_board
        idPreviousTopic:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: id_previous_topic
    lifecycleCallbacks: {  }
