Sima\SmfForumBundle\Entity\SmfTopicLookup:
    type: entity
    table: smf_topic_lookup
    uniqueConstraints:
        topic_text:
            columns:
                - topic_text
    id:
        idTopic:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            id: true
            column: ID_TOPIC
            generator:
                strategy: IDENTITY
    fields:
        idBoard:
            type: smallint
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: ID_BOARD
        topicText:
            type: string
            nullable: false
            length: 120
            fixed: false
            comment: ''
            default: ''
            column: topic_text
    lifecycleCallbacks: {  }
